version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    networks:
      - elk
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
      - './etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    networks:
      - elk
    volumes:
      - './etc/kibana.yml:/usr/share/kibana/config/kibana.yml:ro'
    links:
      - elasticsearch
  nginx:
    image: nginx:alpine
    volumes:
      - './etc/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './dalek:/usr/share/nginx/html:ro'
      - './etc/.htpasswd:/etc/nginx/.htpasswd:ro'
      - './etc/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro'
      - './etc/privkey.pem:/etc/nginx/ssl/privkey.pem:ro'
    links:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - '80:80'
      - '443:443'
    environment:
      - SERVER_DOMAIN
    networks:
      - elk
volumes:
  esdata:
networks:
  elk:
    driver: bridge
